# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AjustesDeOperario.ui'
#
# Created: Mon Aug 24 01:42:56 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AjusteDeOperario(object):
    def setupUi(self, AjusteDeOperario):
        AjusteDeOperario.setObjectName(_fromUtf8("AjusteDeOperario"))
        AjusteDeOperario.resize(360, 600)
        AjusteDeOperario.setMinimumSize(QtCore.QSize(360, 600))
        AjusteDeOperario.setMaximumSize(QtCore.QSize(360, 600))
        self.label_18 = QtGui.QLabel(AjusteDeOperario)
        self.label_18.setGeometry(QtCore.QRect(50, 120, 261, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_15 = QtGui.QLabel(AjusteDeOperario)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 321, 43))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(24)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_20 = QtGui.QLabel(AjusteDeOperario)
        self.label_20.setGeometry(QtCore.QRect(110, 60, 121, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.comboNombre = QtGui.QComboBox(AjusteDeOperario)
        self.comboNombre.setGeometry(QtCore.QRect(100, 80, 140, 33))
        self.comboNombre.setMinimumSize(QtCore.QSize(140, 0))
        self.comboNombre.setObjectName(_fromUtf8("comboNombre"))
        self.widget = QtGui.QWidget(AjusteDeOperario)
        self.widget.setGeometry(QtCore.QRect(10, 150, 341, 437))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.txtNombre = QtGui.QLineEdit(self.widget)
        self.txtNombre.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtNombre.setFont(font)
        self.txtNombre.setObjectName(_fromUtf8("txtNombre"))
        self.horizontalLayout.addWidget(self.txtNombre)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem1 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.txtApellido = QtGui.QLineEdit(self.widget)
        self.txtApellido.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtApellido.setFont(font)
        self.txtApellido.setObjectName(_fromUtf8("txtApellido"))
        self.horizontalLayout_7.addWidget(self.txtApellido)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem2 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.txtDocumento = QtGui.QLineEdit(self.widget)
        self.txtDocumento.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtDocumento.setFont(font)
        self.txtDocumento.setObjectName(_fromUtf8("txtDocumento"))
        self.horizontalLayout_8.addWidget(self.txtDocumento)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.txtClave = QtGui.QLineEdit(self.widget)
        self.txtClave.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtClave.setFont(font)
        self.txtClave.setObjectName(_fromUtf8("txtClave"))
        self.horizontalLayout_9.addWidget(self.txtClave)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem4 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.txtConClave = QtGui.QLineEdit(self.widget)
        self.txtConClave.setMinimumSize(QtCore.QSize(144, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtConClave.setFont(font)
        self.txtConClave.setObjectName(_fromUtf8("txtConClave"))
        self.horizontalLayout_10.addWidget(self.txtConClave)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        spacerItem5 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.txtTelefono = QtGui.QLineEdit(self.widget)
        self.txtTelefono.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtTelefono.setFont(font)
        self.txtTelefono.setObjectName(_fromUtf8("txtTelefono"))
        self.horizontalLayout_13.addWidget(self.txtTelefono)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        spacerItem6 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.txtDireccion = QtGui.QLineEdit(self.widget)
        self.txtDireccion.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtDireccion.setFont(font)
        self.txtDireccion.setObjectName(_fromUtf8("txtDireccion"))
        self.horizontalLayout_14.addWidget(self.txtDireccion)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        spacerItem7 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.txtPregunta = QtGui.QLineEdit(self.widget)
        self.txtPregunta.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtPregunta.setFont(font)
        self.txtPregunta.setObjectName(_fromUtf8("txtPregunta"))
        self.horizontalLayout_15.addWidget(self.txtPregunta)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setToolTip(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_16.addWidget(self.label_17)
        spacerItem8 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.txtRespuesta = QtGui.QLineEdit(self.widget)
        self.txtRespuesta.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.txtRespuesta.setFont(font)
        self.txtRespuesta.setObjectName(_fromUtf8("txtRespuesta"))
        self.horizontalLayout_16.addWidget(self.txtRespuesta)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_19 = QtGui.QLabel(self.widget)
        self.label_19.setMinimumSize(QtCore.QSize(80, 0))
        self.label_19.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setToolTip(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_2.addWidget(self.label_19)
        spacerItem9 = QtGui.QSpacerItem(42, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.comboEstado = QtGui.QComboBox(self.widget)
        self.comboEstado.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.comboEstado.setFont(font)
        self.comboEstado.setObjectName(_fromUtf8("comboEstado"))
        self.comboEstado.addItem(_fromUtf8(""))
        self.comboEstado.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboEstado)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem10 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.btnCrear = QtGui.QPushButton(self.widget)
        self.btnCrear.setObjectName(_fromUtf8("btnCrear"))
        self.horizontalLayout_17.addWidget(self.btnCrear)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_17.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_17)

        self.retranslateUi(AjusteDeOperario)
        QtCore.QMetaObject.connectSlotsByName(AjusteDeOperario)

    def retranslateUi(self, AjusteDeOperario):
        AjusteDeOperario.setWindowTitle(_translate("AjusteDeOperario", "Dialog", None))
        self.label_18.setText(_translate("AjusteDeOperario", "Los campos con asterisco (*) son obligatorios.", None))
        self.label_15.setText(_translate("AjusteDeOperario", "Ajustes de Operario", None))
        self.label_20.setText(_translate("AjusteDeOperario", "Buscar por Nombre", None))
        self.label.setText(_translate("AjusteDeOperario", "Nombres*", None))
        self.label_7.setText(_translate("AjusteDeOperario", "Apellidos*", None))
        self.label_8.setText(_translate("AjusteDeOperario", "Documento*", None))
        self.txtDocumento.setToolTip(_translate("AjusteDeOperario", "<html><head/><body><p>Ingrese la cédula de ciudadanía</p></body></html>", None))
        self.label_9.setText(_translate("AjusteDeOperario", "Clave*", None))
        self.txtClave.setToolTip(_translate("AjusteDeOperario", "<html><head/><body><p>Palabra secreta necesaria para la autenticación de usuario.</p></body></html>", None))
        self.label_10.setText(_translate("AjusteDeOperario", "Confirmar Clave*", None))
        self.label_13.setText(_translate("AjusteDeOperario", "Telefono*", None))
        self.label_14.setText(_translate("AjusteDeOperario", "Dirección*", None))
        self.label_16.setText(_translate("AjusteDeOperario", "Pregunta*", None))
        self.txtPregunta.setToolTip(_translate("AjusteDeOperario", "<html><head/><body><p> Pregunta en caso de que olvides la contraseña</p><p><br/></p></body></html>", None))
        self.label_17.setText(_translate("AjusteDeOperario", "Respuesta*", None))
        self.txtRespuesta.setToolTip(_translate("AjusteDeOperario", "<html><head/><body><p>Respuesta para recuperar contraseña.</p></body></html>", None))
        self.label_19.setText(_translate("AjusteDeOperario", "Estado*", None))
        self.comboEstado.setItemText(0, _translate("AjusteDeOperario", "Inactivo", None))
        self.comboEstado.setItemText(1, _translate("AjusteDeOperario", "Activo", None))
        self.btnCrear.setText(_translate("AjusteDeOperario", "&Actualizar", None))
        self.pushButton_2.setText(_translate("AjusteDeOperario", "Cancelar", None))

