# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambioDeSeguridad.ui'
#
# Created: Mon Aug  3 21:20:44 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_cambioClave(object):
    def setupUi(self, cambioClave):
        cambioClave.setObjectName(_fromUtf8("cambioClave"))
        cambioClave.resize(541, 407)
        self.label = QtGui.QLabel(cambioClave)
        self.label.setGeometry(QtCore.QRect(10, 20, 511, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_8 = QtGui.QLabel(cambioClave)
        self.label_8.setGeometry(QtCore.QRect(90, 80, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(cambioClave)
        self.label_9.setGeometry(QtCore.QRect(340, 80, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.btnModificarClave = QtGui.QPushButton(cambioClave)
        self.btnModificarClave.setGeometry(QtCore.QRect(100, 340, 95, 35))
        self.btnModificarClave.setMinimumSize(QtCore.QSize(95, 30))
        self.btnModificarClave.setMaximumSize(QtCore.QSize(95, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.btnModificarClave.setFont(font)
        self.btnModificarClave.setObjectName(_fromUtf8("btnModificarClave"))
        self.btnModificarPregunta = QtGui.QPushButton(cambioClave)
        self.btnModificarPregunta.setGeometry(QtCore.QRect(340, 340, 95, 30))
        self.btnModificarPregunta.setMinimumSize(QtCore.QSize(95, 30))
        self.btnModificarPregunta.setMaximumSize(QtCore.QSize(95, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.btnModificarPregunta.setFont(font)
        self.btnModificarPregunta.setObjectName(_fromUtf8("btnModificarPregunta"))
        self.widget = QtGui.QWidget(cambioClave)
        self.widget.setGeometry(QtCore.QRect(40, 120, 454, 199))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.txtCLaveVieja = QtGui.QLineEdit(self.widget)
        self.txtCLaveVieja.setMinimumSize(QtCore.QSize(210, 35))
        self.txtCLaveVieja.setMaximumSize(QtCore.QSize(210, 35))
        self.txtCLaveVieja.setObjectName(_fromUtf8("txtCLaveVieja"))
        self.verticalLayout_2.addWidget(self.txtCLaveVieja)
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.txtCLaveNueva = QtGui.QLineEdit(self.widget)
        self.txtCLaveNueva.setMinimumSize(QtCore.QSize(210, 35))
        self.txtCLaveNueva.setMaximumSize(QtCore.QSize(210, 35))
        self.txtCLaveNueva.setObjectName(_fromUtf8("txtCLaveNueva"))
        self.verticalLayout_2.addWidget(self.txtCLaveNueva)
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.txtConCLaveNueva = QtGui.QLineEdit(self.widget)
        self.txtConCLaveNueva.setMinimumSize(QtCore.QSize(210, 35))
        self.txtConCLaveNueva.setMaximumSize(QtCore.QSize(210, 35))
        self.txtConCLaveNueva.setObjectName(_fromUtf8("txtConCLaveNueva"))
        self.verticalLayout_2.addWidget(self.txtConCLaveNueva)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.txtCLaveViejaPre = QtGui.QLineEdit(self.widget)
        self.txtCLaveViejaPre.setMinimumSize(QtCore.QSize(210, 35))
        self.txtCLaveViejaPre.setMaximumSize(QtCore.QSize(210, 35))
        self.txtCLaveViejaPre.setObjectName(_fromUtf8("txtCLaveViejaPre"))
        self.verticalLayout.addWidget(self.txtCLaveViejaPre)
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.txtPregunta = QtGui.QLineEdit(self.widget)
        self.txtPregunta.setMinimumSize(QtCore.QSize(210, 35))
        self.txtPregunta.setMaximumSize(QtCore.QSize(210, 35))
        self.txtPregunta.setObjectName(_fromUtf8("txtPregunta"))
        self.verticalLayout.addWidget(self.txtPregunta)
        self.label_6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.txtRespuesta = QtGui.QLineEdit(self.widget)
        self.txtRespuesta.setMinimumSize(QtCore.QSize(210, 35))
        self.txtRespuesta.setMaximumSize(QtCore.QSize(210, 35))
        self.txtRespuesta.setObjectName(_fromUtf8("txtRespuesta"))
        self.verticalLayout.addWidget(self.txtRespuesta)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(cambioClave)
        QtCore.QMetaObject.connectSlotsByName(cambioClave)

    def retranslateUi(self, cambioClave):
        cambioClave.setWindowTitle(_translate("cambioClave", "Cambio de Contraseña", None))
        self.label.setText(_translate("cambioClave", "Cambios de Pregunta y contraseña", None))
        self.label_8.setText(_translate("cambioClave", "Contraseña", None))
        self.label_9.setText(_translate("cambioClave", "Pregunta", None))
        self.btnModificarClave.setText(_translate("cambioClave", "Modificar", None))
        self.btnModificarPregunta.setText(_translate("cambioClave", "Modificar", None))
        self.label_2.setText(_translate("cambioClave", "ingrese la contraseña actual", None))
        self.label_3.setText(_translate("cambioClave", "ingrese la nueva contraseña ", None))
        self.label_4.setText(_translate("cambioClave", "Confirme la nueva contraseña ", None))
        self.label_7.setText(_translate("cambioClave", "ingrese la contraseña actual", None))
        self.label_5.setText(_translate("cambioClave", "ingrese la nueva Pregunta", None))
        self.label_6.setText(_translate("cambioClave", "ingrese la nueva respuesta", None))

