# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CrearUsuario.ui'
#
# Created: Mon Jul 27 23:12:06 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vtnCrearUsuario(object):
    def setupUi(self, vtnCrearUsuario):
        vtnCrearUsuario.setObjectName(_fromUtf8("vtnCrearUsuario"))
        vtnCrearUsuario.resize(355, 480)
        vtnCrearUsuario.setMinimumSize(QtCore.QSize(355, 480))
        vtnCrearUsuario.setMaximumSize(QtCore.QSize(355, 480))
        vtnCrearUsuario.setToolTip(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(vtnCrearUsuario)
        self.label_15.setGeometry(QtCore.QRect(60, 10, 235, 43))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(24)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_18 = QtGui.QLabel(vtnCrearUsuario)
        self.label_18.setGeometry(QtCore.QRect(50, 60, 261, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.splitter = QtGui.QSplitter(vtnCrearUsuario)
        self.splitter.setGeometry(QtCore.QRect(10, 89, 336, 382))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.txtNombre = QtGui.QLineEdit(self.widget)
        self.txtNombre.setMinimumSize(QtCore.QSize(120, 0))
        self.txtNombre.setObjectName(_fromUtf8("txtNombre"))
        self.horizontalLayout.addWidget(self.txtNombre)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem1 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.txtApellido = QtGui.QLineEdit(self.widget)
        self.txtApellido.setMinimumSize(QtCore.QSize(120, 0))
        self.txtApellido.setObjectName(_fromUtf8("txtApellido"))
        self.horizontalLayout_7.addWidget(self.txtApellido)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        spacerItem2 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.txtDocumento = QtGui.QLineEdit(self.widget)
        self.txtDocumento.setMinimumSize(QtCore.QSize(120, 0))
        self.txtDocumento.setObjectName(_fromUtf8("txtDocumento"))
        self.horizontalLayout_8.addWidget(self.txtDocumento)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.txtClave = QtGui.QLineEdit(self.widget)
        self.txtClave.setMinimumSize(QtCore.QSize(120, 0))
        self.txtClave.setObjectName(_fromUtf8("txtClave"))
        self.horizontalLayout_9.addWidget(self.txtClave)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(100, 0))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem4 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.txtConClave = QtGui.QLineEdit(self.widget)
        self.txtConClave.setMinimumSize(QtCore.QSize(120, 0))
        self.txtConClave.setObjectName(_fromUtf8("txtConClave"))
        self.horizontalLayout_10.addWidget(self.txtConClave)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        spacerItem5 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.txtTelefono = QtGui.QLineEdit(self.widget)
        self.txtTelefono.setMinimumSize(QtCore.QSize(120, 0))
        self.txtTelefono.setObjectName(_fromUtf8("txtTelefono"))
        self.horizontalLayout_13.addWidget(self.txtTelefono)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_14 = QtGui.QLabel(self.widget)
        self.label_14.setMinimumSize(QtCore.QSize(100, 0))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        spacerItem6 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.txtDireccion = QtGui.QLineEdit(self.widget)
        self.txtDireccion.setMinimumSize(QtCore.QSize(120, 0))
        self.txtDireccion.setObjectName(_fromUtf8("txtDireccion"))
        self.horizontalLayout_14.addWidget(self.txtDireccion)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.widget)
        self.label_16.setMinimumSize(QtCore.QSize(100, 0))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        spacerItem7 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.txtPregunta = QtGui.QLineEdit(self.widget)
        self.txtPregunta.setMinimumSize(QtCore.QSize(120, 0))
        self.txtPregunta.setObjectName(_fromUtf8("txtPregunta"))
        self.horizontalLayout_15.addWidget(self.txtPregunta)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_17 = QtGui.QLabel(self.widget)
        self.label_17.setMinimumSize(QtCore.QSize(100, 0))
        self.label_17.setToolTip(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_16.addWidget(self.label_17)
        spacerItem8 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.txtRespuesta = QtGui.QLineEdit(self.widget)
        self.txtRespuesta.setMinimumSize(QtCore.QSize(120, 0))
        self.txtRespuesta.setObjectName(_fromUtf8("txtRespuesta"))
        self.horizontalLayout_16.addWidget(self.txtRespuesta)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem9 = QtGui.QSpacerItem(100, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_18.addItem(spacerItem9)
        spacerItem10 = QtGui.QSpacerItem(100, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_18.addItem(spacerItem10)
        spacerItem11 = QtGui.QSpacerItem(120, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.widget2 = QtGui.QWidget(self.splitter)
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem12 = QtGui.QSpacerItem(150, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.btnCrear = QtGui.QPushButton(self.widget2)
        self.btnCrear.setObjectName(_fromUtf8("btnCrear"))
        self.horizontalLayout_17.addWidget(self.btnCrear)
        self.pushButton_2 = QtGui.QPushButton(self.widget2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_17.addWidget(self.pushButton_2)

        self.retranslateUi(vtnCrearUsuario)
        QtCore.QMetaObject.connectSlotsByName(vtnCrearUsuario)
        vtnCrearUsuario.setTabOrder(self.txtNombre, self.txtApellido)
        vtnCrearUsuario.setTabOrder(self.txtApellido, self.txtDocumento)
        vtnCrearUsuario.setTabOrder(self.txtDocumento, self.txtClave)
        vtnCrearUsuario.setTabOrder(self.txtClave, self.txtConClave)
        vtnCrearUsuario.setTabOrder(self.txtConClave, self.txtTelefono)
        vtnCrearUsuario.setTabOrder(self.txtTelefono, self.txtDireccion)
        vtnCrearUsuario.setTabOrder(self.txtDireccion, self.txtPregunta)
        vtnCrearUsuario.setTabOrder(self.txtPregunta, self.txtRespuesta)
        vtnCrearUsuario.setTabOrder(self.txtRespuesta, self.btnCrear)
        vtnCrearUsuario.setTabOrder(self.btnCrear, self.pushButton_2)

    def retranslateUi(self, vtnCrearUsuario):
        vtnCrearUsuario.setWindowTitle(_translate("vtnCrearUsuario", "Crear Operario", None))
        self.label_15.setText(_translate("vtnCrearUsuario", "Crear Operario", None))
        self.label_18.setText(_translate("vtnCrearUsuario", "Los campos con asterisco (*) son obligatorios.", None))
        self.label.setText(_translate("vtnCrearUsuario", "Nombres*", None))
        self.label_7.setText(_translate("vtnCrearUsuario", "Apellidos*", None))
        self.label_8.setText(_translate("vtnCrearUsuario", "Documento*", None))
        self.txtDocumento.setToolTip(_translate("vtnCrearUsuario", "<html><head/><body><p>Ingrese la cédula de ciudadanía</p></body></html>", None))
        self.label_9.setText(_translate("vtnCrearUsuario", "Clave*", None))
        self.txtClave.setToolTip(_translate("vtnCrearUsuario", "<html><head/><body><p>Palabra secreta necesaria para la autenticación de usuario.</p></body></html>", None))
        self.label_10.setText(_translate("vtnCrearUsuario", "Confirmar Clave*", None))
        self.label_13.setText(_translate("vtnCrearUsuario", "Telefono*", None))
        self.label_14.setText(_translate("vtnCrearUsuario", "Dirección", None))
        self.label_16.setText(_translate("vtnCrearUsuario", "Pregunta*", None))
        self.txtPregunta.setToolTip(_translate("vtnCrearUsuario", "<html><head/><body><p> Pregunta en caso de que olvides la contraseña</p><p><br/></p></body></html>", None))
        self.label_17.setText(_translate("vtnCrearUsuario", "Respuesta*", None))
        self.txtRespuesta.setToolTip(_translate("vtnCrearUsuario", "<html><head/><body><p>Respuesta para recuperar contraseña.</p></body></html>", None))
        self.btnCrear.setText(_translate("vtnCrearUsuario", "&Crear", None))
        self.pushButton_2.setText(_translate("vtnCrearUsuario", "Cancelar", None))

