# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CrearCliente.ui'
#
# Created: Thu Aug 20 07:51:59 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_crearCliente(object):
    def setupUi(self, crearCliente):
        crearCliente.setObjectName(_fromUtf8("crearCliente"))
        crearCliente.resize(435, 340)
        crearCliente.setMinimumSize(QtCore.QSize(435, 340))
        crearCliente.setMaximumSize(QtCore.QSize(435, 340))
        self.layoutWidget = QtGui.QWidget(crearCliente)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 80, 394, 32))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(110, 30))
        self.label_2.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.txtNombre = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.txtNombre.sizePolicy().hasHeightForWidth())
        self.txtNombre.setSizePolicy(sizePolicy)
        self.txtNombre.setMinimumSize(QtCore.QSize(150, 30))
        self.txtNombre.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.txtNombre.setFont(font)
        self.txtNombre.setText(_fromUtf8(""))
        self.txtNombre.setObjectName(_fromUtf8("txtNombre"))
        self.horizontalLayout.addWidget(self.txtNombre)
        self.layoutWidget_2 = QtGui.QWidget(crearCliente)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 180, 394, 32))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(110, 30))
        self.label_4.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem1 = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.txtTlefono = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.txtTlefono.sizePolicy().hasHeightForWidth())
        self.txtTlefono.setSizePolicy(sizePolicy)
        self.txtTlefono.setMinimumSize(QtCore.QSize(150, 30))
        self.txtTlefono.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.txtTlefono.setFont(font)
        self.txtTlefono.setText(_fromUtf8(""))
        self.txtTlefono.setObjectName(_fromUtf8("txtTlefono"))
        self.horizontalLayout_3.addWidget(self.txtTlefono)
        self.label = QtGui.QLabel(crearCliente)
        self.label.setGeometry(QtCore.QRect(110, 20, 221, 40))
        self.label.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget_3 = QtGui.QWidget(crearCliente)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 230, 394, 32))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(125, 30))
        self.label_5.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(110, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.txtDireccion = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.txtDireccion.sizePolicy().hasHeightForWidth())
        self.txtDireccion.setSizePolicy(sizePolicy)
        self.txtDireccion.setMinimumSize(QtCore.QSize(150, 30))
        self.txtDireccion.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.txtDireccion.setFont(font)
        self.txtDireccion.setText(_fromUtf8(""))
        self.txtDireccion.setObjectName(_fromUtf8("txtDireccion"))
        self.horizontalLayout_4.addWidget(self.txtDireccion)
        self.layoutWidget_4 = QtGui.QWidget(crearCliente)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 130, 394, 32))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(110, 30))
        self.label_3.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.txtApellido = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.txtApellido.sizePolicy().hasHeightForWidth())
        self.txtApellido.setSizePolicy(sizePolicy)
        self.txtApellido.setMinimumSize(QtCore.QSize(150, 30))
        self.txtApellido.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.txtApellido.setFont(font)
        self.txtApellido.setText(_fromUtf8(""))
        self.txtApellido.setObjectName(_fromUtf8("txtApellido"))
        self.horizontalLayout_2.addWidget(self.txtApellido)
        self.btnCrearCliente = QtGui.QPushButton(crearCliente)
        self.btnCrearCliente.setGeometry(QtCore.QRect(220, 280, 100, 30))
        self.btnCrearCliente.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.btnCrearCliente.setFont(font)
        self.btnCrearCliente.setObjectName(_fromUtf8("btnCrearCliente"))
        self.btnCerrar = QtGui.QPushButton(crearCliente)
        self.btnCerrar.setGeometry(QtCore.QRect(110, 280, 100, 30))
        self.btnCerrar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.btnCerrar.setFont(font)
        self.btnCerrar.setObjectName(_fromUtf8("btnCerrar"))

        self.retranslateUi(crearCliente)
        QtCore.QMetaObject.connectSlotsByName(crearCliente)

    def retranslateUi(self, crearCliente):
        crearCliente.setWindowTitle(_translate("crearCliente", "Creación de Cliente", None))
        self.label_2.setText(_translate("crearCliente", "Nombre", None))
        self.txtNombre.setToolTip(_translate("crearCliente", "Ingrese Nombre del Cliente", None))
        self.label_4.setText(_translate("crearCliente", "Teléfono", None))
        self.txtTlefono.setToolTip(_translate("crearCliente", "Ingrese Teléfono del Cliente", None))
        self.label.setText(_translate("crearCliente", "Ingresar cliente", None))
        self.label_5.setText(_translate("crearCliente", "Documento", None))
        self.txtDireccion.setToolTip(_translate("crearCliente", "Ingrese Dirección del Cliente", None))
        self.label_3.setText(_translate("crearCliente", "Apellidos", None))
        self.txtApellido.setToolTip(_translate("crearCliente", "Ingrese Apellidos del Cliente", None))
        self.btnCrearCliente.setToolTip(_translate("crearCliente", "Crear Cliente", None))
        self.btnCrearCliente.setText(_translate("crearCliente", "Crear", None))
        self.btnCrearCliente.setShortcut(_translate("crearCliente", "Return", None))
        self.btnCerrar.setToolTip(_translate("crearCliente", "Cerrar ventana", None))
        self.btnCerrar.setText(_translate("crearCliente", "&Cerrar", None))
        self.btnCerrar.setShortcut(_translate("crearCliente", "Ctrl+C", None))

