# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CrearVehiculo.ui'
#
# Created: Thu Aug 13 12:49:24 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CrearTipoVehiculo(object):
    def setupUi(self, CrearTipoVehiculo):
        CrearTipoVehiculo.setObjectName(_fromUtf8("CrearTipoVehiculo"))
        CrearTipoVehiculo.resize(438, 419)
        self.layoutWidget = QtGui.QWidget(CrearTipoVehiculo)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 170, 186, 34))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.spinFraccion = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.spinFraccion.setFont(font)
        self.spinFraccion.setMaximum(999999)
        self.spinFraccion.setObjectName(_fromUtf8("spinFraccion"))
        self.horizontalLayout_6.addWidget(self.spinFraccion)
        self.layoutWidget_5 = QtGui.QWidget(CrearTipoVehiculo)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 220, 186, 34))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_5)
        self.label_13.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_10.addWidget(self.label_13)
        self.spinHora = QtGui.QSpinBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.spinHora.setFont(font)
        self.spinHora.setMaximum(999999)
        self.spinHora.setObjectName(_fromUtf8("spinHora"))
        self.horizontalLayout_10.addWidget(self.spinHora)
        self.btnCerrar = QtGui.QPushButton(CrearTipoVehiculo)
        self.btnCerrar.setGeometry(QtCore.QRect(120, 340, 85, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(11)
        self.btnCerrar.setFont(font)
        self.btnCerrar.setObjectName(_fromUtf8("btnCerrar"))
        self.label_6 = QtGui.QLabel(CrearTipoVehiculo)
        self.label_6.setGeometry(QtCore.QRect(80, 30, 300, 40))
        self.label_6.setMinimumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(CrearTipoVehiculo)
        self.label_8.setGeometry(QtCore.QRect(180, 140, 100, 20))
        self.label_8.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.layoutWidget_9 = QtGui.QWidget(CrearTipoVehiculo)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 270, 186, 34))
        self.layoutWidget_9.setObjectName(_fromUtf8("layoutWidget_9"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_17 = QtGui.QLabel(self.layoutWidget_9)
        self.label_17.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_14.addWidget(self.label_17)
        self.spinEspecial = QtGui.QSpinBox(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.spinEspecial.setFont(font)
        self.spinEspecial.setMaximum(999999)
        self.spinEspecial.setObjectName(_fromUtf8("spinEspecial"))
        self.horizontalLayout_14.addWidget(self.spinEspecial)
        self.btnCrearVh = QtGui.QPushButton(CrearTipoVehiculo)
        self.btnCrearVh.setGeometry(QtCore.QRect(230, 340, 85, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(11)
        self.btnCrearVh.setFont(font)
        self.btnCrearVh.setObjectName(_fromUtf8("btnCrearVh"))
        self.layoutWidget_7 = QtGui.QWidget(CrearTipoVehiculo)
        self.layoutWidget_7.setGeometry(QtCore.QRect(230, 220, 186, 34))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_15 = QtGui.QLabel(self.layoutWidget_7)
        self.label_15.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_12.addWidget(self.label_15)
        self.spinMes = QtGui.QSpinBox(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.spinMes.setFont(font)
        self.spinMes.setMaximum(999999)
        self.spinMes.setObjectName(_fromUtf8("spinMes"))
        self.horizontalLayout_12.addWidget(self.spinMes)
        self.layoutWidget_4 = QtGui.QWidget(CrearTipoVehiculo)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 80, 394, 32))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(110)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(110, 30))
        self.label_7.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.txtNombreVh = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.txtNombreVh.sizePolicy().hasHeightForWidth())
        self.txtNombreVh.setSizePolicy(sizePolicy)
        self.txtNombreVh.setMinimumSize(QtCore.QSize(150, 30))
        self.txtNombreVh.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.txtNombreVh.setFont(font)
        self.txtNombreVh.setText(_fromUtf8(""))
        self.txtNombreVh.setObjectName(_fromUtf8("txtNombreVh"))
        self.horizontalLayout_5.addWidget(self.txtNombreVh)
        self.layoutWidget_8 = QtGui.QWidget(CrearTipoVehiculo)
        self.layoutWidget_8.setGeometry(QtCore.QRect(230, 270, 186, 34))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_16 = QtGui.QLabel(self.layoutWidget_8)
        self.label_16.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_13.addWidget(self.label_16)
        self.spinCeldas = QtGui.QSpinBox(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.spinCeldas.setFont(font)
        self.spinCeldas.setMaximum(999999)
        self.spinCeldas.setObjectName(_fromUtf8("spinCeldas"))
        self.horizontalLayout_13.addWidget(self.spinCeldas)
        self.layoutWidget_6 = QtGui.QWidget(CrearTipoVehiculo)
        self.layoutWidget_6.setGeometry(QtCore.QRect(230, 170, 186, 34))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_6)
        self.label_14.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_11.addWidget(self.label_14)
        self.spinDia = QtGui.QSpinBox(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.spinDia.setFont(font)
        self.spinDia.setMaximum(999999)
        self.spinDia.setObjectName(_fromUtf8("spinDia"))
        self.horizontalLayout_11.addWidget(self.spinDia)

        self.retranslateUi(CrearTipoVehiculo)
        QtCore.QMetaObject.connectSlotsByName(CrearTipoVehiculo)
        CrearTipoVehiculo.setTabOrder(self.txtNombreVh, self.spinFraccion)
        CrearTipoVehiculo.setTabOrder(self.spinFraccion, self.spinHora)
        CrearTipoVehiculo.setTabOrder(self.spinHora, self.spinDia)
        CrearTipoVehiculo.setTabOrder(self.spinDia, self.spinMes)
        CrearTipoVehiculo.setTabOrder(self.spinMes, self.spinEspecial)
        CrearTipoVehiculo.setTabOrder(self.spinEspecial, self.spinCeldas)
        CrearTipoVehiculo.setTabOrder(self.spinCeldas, self.btnCrearVh)
        CrearTipoVehiculo.setTabOrder(self.btnCrearVh, self.btnCerrar)

    def retranslateUi(self, CrearTipoVehiculo):
        CrearTipoVehiculo.setWindowTitle(_translate("CrearTipoVehiculo", "Crear Tipo de Vehículo", None))
        self.label_9.setText(_translate("CrearTipoVehiculo", "Fracción", None))
        self.spinFraccion.setToolTip(_translate("CrearTipoVehiculo", "Ingrese valor de la Fracción", None))
        self.label_13.setText(_translate("CrearTipoVehiculo", "Hora", None))
        self.spinHora.setToolTip(_translate("CrearTipoVehiculo", "Ingrese valor de la Hora", None))
        self.btnCerrar.setToolTip(_translate("CrearTipoVehiculo", "Cerrar ventana", None))
        self.btnCerrar.setText(_translate("CrearTipoVehiculo", "&Cerrar", None))
        self.btnCerrar.setShortcut(_translate("CrearTipoVehiculo", "Ctrl+C", None))
        self.label_6.setText(_translate("CrearTipoVehiculo", "Crear tipo de Vehículo", None))
        self.label_8.setText(_translate("CrearTipoVehiculo", "Tarifa por:", None))
        self.label_17.setText(_translate("CrearTipoVehiculo", "Especial", None))
        self.spinEspecial.setToolTip(_translate("CrearTipoVehiculo", "Ingrese valor hora especial", None))
        self.btnCrearVh.setToolTip(_translate("CrearTipoVehiculo", "Crear tipo de vehículo", None))
        self.btnCrearVh.setText(_translate("CrearTipoVehiculo", "Crear", None))
        self.btnCrearVh.setShortcut(_translate("CrearTipoVehiculo", "Return", None))
        self.label_15.setText(_translate("CrearTipoVehiculo", "Mes", None))
        self.spinMes.setToolTip(_translate("CrearTipoVehiculo", "Ingrese valor del Mes", None))
        self.label_7.setText(_translate("CrearTipoVehiculo", "Nombre", None))
        self.txtNombreVh.setToolTip(_translate("CrearTipoVehiculo", "Escriba nombre del tipo de vehículo", None))
        self.label_16.setText(_translate("CrearTipoVehiculo", "# Celdas", None))
        self.spinCeldas.setToolTip(_translate("CrearTipoVehiculo", "Ingrese numero de celdas", None))
        self.label_14.setText(_translate("CrearTipoVehiculo", "Día", None))
        self.spinDia.setToolTip(_translate("CrearTipoVehiculo", "Ingrese valor del Día", None))

