# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServicioDeAlquiler.ui'
#
# Created: Tue Aug 11 00:13:47 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 270, 151, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(320, 310, 175, 50))
        self.lineEdit.setMinimumSize(QtCore.QSize(175, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(22)
        self.lineEdit.setFont(font)
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 390, 140, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.labelRol = QtGui.QLabel(self.centralwidget)
        self.labelRol.setGeometry(QtCore.QRect(20, 26, 150, 35))
        self.labelRol.setMinimumSize(QtCore.QSize(90, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.labelRol.setFont(font)
        self.labelRol.setObjectName(_fromUtf8("labelRol"))
        self.labeNombreUsuario = QtGui.QLabel(self.centralwidget)
        self.labeNombreUsuario.setGeometry(QtCore.QRect(20, 60, 150, 35))
        self.labeNombreUsuario.setMinimumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.labeNombreUsuario.setFont(font)
        self.labeNombreUsuario.setObjectName(_fromUtf8("labeNombreUsuario"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 100, 346, 148))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lcdHoras = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdHoras.setMinimumSize(QtCore.QSize(155, 130))
        self.lcdHoras.setNumDigits(2)
        self.lcdHoras.setObjectName(_fromUtf8("lcdHoras"))
        self.horizontalLayout.addWidget(self.lcdHoras)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.lcdMinutos = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdMinutos.setMinimumSize(QtCore.QSize(155, 130))
        self.lcdMinutos.setNumDigits(2)
        self.lcdMinutos.setObjectName(_fromUtf8("lcdMinutos"))
        self.horizontalLayout.addWidget(self.lcdMinutos)
        self.labeNombreUsuario_2 = QtGui.QLabel(self.centralwidget)
        self.labeNombreUsuario_2.setGeometry(QtCore.QRect(320, 10, 150, 35))
        self.labeNombreUsuario_2.setMinimumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(14)
        self.labeNombreUsuario_2.setFont(font)
        self.labeNombreUsuario_2.setObjectName(_fromUtf8("labeNombreUsuario_2"))
        self.labelParqueadero = QtGui.QLabel(self.centralwidget)
        self.labelParqueadero.setGeometry(QtCore.QRect(320, 50, 150, 35))
        self.labelParqueadero.setMinimumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans [unknown]"))
        font.setPointSize(16)
        self.labelParqueadero.setFont(font)
        self.labelParqueadero.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelParqueadero.setObjectName(_fromUtf8("labelParqueadero"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Usuario = QtGui.QMenu(self.menubar)
        self.menu_Usuario.setObjectName(_fromUtf8("menu_Usuario"))
        self.menuGestion = QtGui.QMenu(self.menu_Usuario)
        self.menuGestion.setObjectName(_fromUtf8("menuGestion"))
        self.menuParqueadero = QtGui.QMenu(self.menubar)
        self.menuParqueadero.setObjectName(_fromUtf8("menuParqueadero"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionPerfil_de_usuario = QtGui.QAction(MainWindow)
        self.actionPerfil_de_usuario.setObjectName(_fromUtf8("actionPerfil_de_usuario"))
        self.actionPerfil = QtGui.QAction(MainWindow)
        self.actionPerfil.setObjectName(_fromUtf8("actionPerfil"))
        self.actionCerraSesion = QtGui.QAction(MainWindow)
        self.actionCerraSesion.setObjectName(_fromUtf8("actionCerraSesion"))
        self.actionCerra = QtGui.QAction(MainWindow)
        self.actionCerra.setObjectName(_fromUtf8("actionCerra"))
        self.actionAjustes = QtGui.QAction(MainWindow)
        self.actionAjustes.setObjectName(_fromUtf8("actionAjustes"))
        self.actionCrearUsuario = QtGui.QAction(MainWindow)
        self.actionCrearUsuario.setObjectName(_fromUtf8("actionCrearUsuario"))
        self.menuGestion.addAction(self.actionCrearUsuario)
        self.menu_Usuario.addSeparator()
        self.menu_Usuario.addAction(self.actionPerfil)
        self.menu_Usuario.addAction(self.menuGestion.menuAction())
        self.menu_Usuario.addSeparator()
        self.menu_Usuario.addAction(self.actionCerraSesion)
        self.menu_Usuario.addAction(self.actionCerra)
        self.menuParqueadero.addAction(self.actionAjustes)
        self.menubar.addAction(self.menu_Usuario.menuAction())
        self.menubar.addAction(self.menuParqueadero.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Servicio se alquiler", None))
        self.label.setText(_translate("MainWindow", "Ingrese placa", None))
        self.pushButton.setText(_translate("MainWindow", "Ingresar", None))
        self.pushButton.setShortcut(_translate("MainWindow", "Return", None))
        self.labelRol.setText(_translate("MainWindow", "Rol", None))
        self.labeNombreUsuario.setText(_translate("MainWindow", "Nombre usuario", None))
        self.label_3.setText(_translate("MainWindow", "ø", None))
        self.label_2.setText(_translate("MainWindow", "ø", None))
        self.labeNombreUsuario_2.setText(_translate("MainWindow", "Parqueadero", None))
        self.labelParqueadero.setText(_translate("MainWindow", "Parqueadero", None))
        self.menu_Usuario.setTitle(_translate("MainWindow", "&Usuario", None))
        self.menuGestion.setTitle(_translate("MainWindow", "Gestion", None))
        self.menuParqueadero.setTitle(_translate("MainWindow", "Parqueadero", None))
        self.actionPerfil_de_usuario.setText(_translate("MainWindow", "Perfil de usuario", None))
        self.actionPerfil.setText(_translate("MainWindow", "Perfil", None))
        self.actionPerfil.setShortcut(_translate("MainWindow", "Alt+P", None))
        self.actionCerraSesion.setText(_translate("MainWindow", "Cerra Sesión", None))
        self.actionCerra.setText(_translate("MainWindow", "Cerra", None))
        self.actionAjustes.setText(_translate("MainWindow", "Ajustes", None))
        self.actionAjustes.setShortcut(_translate("MainWindow", "Alt+A", None))
        self.actionCrearUsuario.setText(_translate("MainWindow", "Crear ", None))
        self.actionCrearUsuario.setShortcut(_translate("MainWindow", "Alt+N", None))

